<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>false</IsPackable><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../CSweet.Compute.Runtime/CSweet.Compute.Runtime.csproj" /></ItemGroup>
<ItemGroup><PackageReference Include="CSweet.Isolation.HyperV" /><PackageReference Include="Microsoft.Extensions.Hosting" /><PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" /></ItemGroup>
</Project>
