<Project>
  <ItemGroup Condition="'$(UsesOfficeContracts)' == 'true'">
    <ProjectReference Condition="'$(UseLocalOfficeContracts)' == 'true'"
                      Include="$(CSweetOfficeContractsRepositoryRoot)\src\CSweet.Office.Contracts\CSweet.Office.Contracts.csproj" />
    <PackageReference Condition="'$(UseLocalOfficeContracts)' != 'true'"
                      Include="CSweet.Office.Contracts" />
  </ItemGroup>
</Project>
