<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CSweet.AgentRuntime.Abstractions\CSweet.AgentRuntime.Abstractions.csproj" />
    <ProjectReference Include="..\CSweet.AgentRuntime.AppleVirtualization\CSweet.AgentRuntime.AppleVirtualization.csproj" />
    <ProjectReference Include="..\CSweet.AgentRuntime.Firecracker\CSweet.AgentRuntime.Firecracker.csproj" />
    <ProjectReference Include="..\CSweet.AgentRuntime.HyperV\CSweet.AgentRuntime.HyperV.csproj" />
    <ProjectReference Include="..\CSweet.AgentRuntime.LocalRpc\CSweet.AgentRuntime.LocalRpc.csproj" />
    <ProjectReference Include="..\CSweet.AgentRuntime.Protocol\CSweet.AgentRuntime.Protocol.csproj" />
  </ItemGroup>
</Project>
